# Generated by Django 3.2 on 2021-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('tag', models.CharField(choices=[('BUG', 'BUG'), ('IMPROVEMENT', 'IMPROVEMENT'), ('TASK', 'TASK')], max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=12)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED')], max_length=21)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
