# Generated by Django 3.2 on 2021-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('type', models.CharField(choices=[('BACK_END', 'BACK_END'), ('FRONT_END', 'FRONT_END'), ('IOS', 'IOS'), ('ANDROID', 'ANDROID')], max_length=10)),
            ],
        ),
    ]
